<?
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true) die();
global $goods_chain_info;
$goods_chain_info = false;

$APPLICATION->IncludeComponent("bitrix:breadcrumb", "main", array(
    "START_FROM" => "0",
    "PATH"       => "",
));

$ElementID = $APPLICATION->IncludeComponent(
	"bitrix:catalog.element", 
	"product_detail1", 
	array(
		"IBLOCK_TYPE" => "CATALOG",
		"IBLOCK_ID" => $arParams["IBLOCK_ID"],
		"PROPERTY_CODE" => array(
			0 => "",
			1 => $arParams["DETAIL_PROPERTY_CODE"],
			2 => "",
		),
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"SET_CANONICAL_URL" => "N",
		"BASKET_URL" => $arParams["BASKET_URL"],
		"ACTION_VARIABLE" => $arParams["ACTION_VARIABLE"],
		"PRODUCT_ID_VARIABLE" => $arParams["PRODUCT_ID_VARIABLE"],
		"SECTION_ID_VARIABLE" => $arParams["SECTION_ID_VARIABLE"],
		"CHECK_SECTION_ID_VARIABLE" => "N",
		"PRODUCT_QUANTITY_VARIABLE" => $arParams["PRODUCT_QUANTITY_VARIABLE"],
		"PRODUCT_PROPS_VARIABLE" => $arParams["PRODUCT_PROPS_VARIABLE"],
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => $arParams["CACHE_TIME"],
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"MESSAGE_404" => $arParams["MESSAGE_404"],
		"SET_STATUS_404" => "N",
		"SHOW_404" => "N",
		"FILE_404" => $arParams["FILE_404"],
		"PRICE_CODE" => array(
			0 => "vladivostok",
			1 => "ussurijsk",
			2 => "arsenev",
			3 => "naxodka",
			4 => "komsomolsk_na_amure",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => $arParams["SHOW_PRICE_COUNT"],
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"LINK_IBLOCK_TYPE" => $arParams["LINK_IBLOCK_TYPE"],
		"LINK_IBLOCK_ID" => $arParams["LINK_IBLOCK_ID"],
		"LINK_PROPERTY_SID" => $arParams["LINK_PROPERTY_SID"],
		"LINK_ELEMENTS_URL" => $arParams["LINK_ELEMENTS_URL"],
		"OFFERS_CART_PROPERTIES" => $arParams["OFFERS_CART_PROPERTIES"],
		"OFFERS_FIELD_CODE" => $arParams["DETAIL_OFFERS_FIELD_CODE"],
		"OFFERS_PROPERTY_CODE" => $arParams["DETAIL_OFFERS_PROPERTY_CODE"],
		"OFFERS_SORT_FIELD" => $arParams["OFFERS_SORT_FIELD"],
		"OFFERS_SORT_ORDER" => $arParams["OFFERS_SORT_ORDER"],
		"OFFERS_SORT_FIELD2" => $arParams["OFFERS_SORT_FIELD2"],
		"OFFERS_SORT_ORDER2" => $arParams["OFFERS_SORT_ORDER2"],
		"ELEMENT_ID" => $arResult["VARIABLES"]["ELEMENT_ID"],
		"ELEMENT_CODE" => $arResult["VARIABLES"]["ELEMENT_CODE"],
		"SECTION_ID" => $arResult["VARIABLES"]["SECTION_ID"],
		"SECTION_CODE" => $arResult["VARIABLES"]["SECTION_CODE"],
		"SECTION_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
		"DETAIL_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["element"],
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => $arParams["CURRENCY_ID"],
		"HIDE_NOT_AVAILABLE" => $arParams["HIDE_NOT_AVAILABLE"],
		"USE_ELEMENT_COUNTER" => "N",
		"SHOW_DEACTIVATED" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"ADD_PICT_PROP" => $arParams["ADD_PICT_PROP"],
		"LABEL_PROP" => $arParams["LABEL_PROP"],
		"OFFER_ADD_PICT_PROP" => $arParams["OFFER_ADD_PICT_PROP"],
		"OFFER_TREE_PROPS" => $arParams["OFFER_TREE_PROPS"],
		"PRODUCT_SUBSCRIPTION" => $arParams["PRODUCT_SUBSCRIPTION"],
		"SHOW_DISCOUNT_PERCENT" => $arParams["SHOW_DISCOUNT_PERCENT"],
		"SHOW_OLD_PRICE" => $arParams["SHOW_OLD_PRICE"],
		"SHOW_MAX_QUANTITY" => $arParams["DETAIL_SHOW_MAX_QUANTITY"],
		"MESS_BTN_BUY" => $arParams["MESS_BTN_BUY"],
		"MESS_BTN_ADD_TO_BASKET" => $arParams["MESS_BTN_ADD_TO_BASKET"],
		"MESS_BTN_SUBSCRIBE" => $arParams["MESS_BTN_SUBSCRIBE"],
		"MESS_BTN_COMPARE" => $arParams["MESS_BTN_COMPARE"],
		"MESS_NOT_AVAILABLE" => $arParams["MESS_NOT_AVAILABLE"],
		"USE_VOTE_RATING" => $arParams["DETAIL_USE_VOTE_RATING"],
		"VOTE_DISPLAY_AS_RATING" => (isset($arParams["DETAIL_VOTE_DISPLAY_AS_RATING"])?$arParams["DETAIL_VOTE_DISPLAY_AS_RATING"]:""),
		"USE_COMMENTS" => $arParams["DETAIL_USE_COMMENTS"],
		"BLOG_USE" => (isset($arParams["DETAIL_BLOG_USE"])?$arParams["DETAIL_BLOG_USE"]:""),
		"BLOG_URL" => (isset($arParams["DETAIL_BLOG_URL"])?$arParams["DETAIL_BLOG_URL"]:""),
		"BLOG_EMAIL_NOTIFY" => (isset($arParams["DETAIL_BLOG_EMAIL_NOTIFY"])?$arParams["DETAIL_BLOG_EMAIL_NOTIFY"]:""),
		"VK_USE" => (isset($arParams["DETAIL_VK_USE"])?$arParams["DETAIL_VK_USE"]:""),
		"VK_API_ID" => (isset($arParams["DETAIL_VK_API_ID"])?$arParams["DETAIL_VK_API_ID"]:"API_ID"),
		"FB_USE" => (isset($arParams["DETAIL_FB_USE"])?$arParams["DETAIL_FB_USE"]:""),
		"FB_APP_ID" => (isset($arParams["DETAIL_FB_APP_ID"])?$arParams["DETAIL_FB_APP_ID"]:""),
		"BRAND_USE" => (isset($arParams["DETAIL_BRAND_USE"])?$arParams["DETAIL_BRAND_USE"]:"N"),
		"BRAND_PROP_CODE" => (isset($arParams["DETAIL_BRAND_PROP_CODE"])?$arParams["DETAIL_BRAND_PROP_CODE"]:""),
		"DISPLAY_NAME" => (isset($arParams["DETAIL_DISPLAY_NAME"])?$arParams["DETAIL_DISPLAY_NAME"]:""),
		"ADD_DETAIL_TO_SLIDER" => (isset($arParams["DETAIL_ADD_DETAIL_TO_SLIDER"])?$arParams["DETAIL_ADD_DETAIL_TO_SLIDER"]:""),
		"TEMPLATE_THEME" => (isset($arParams["TEMPLATE_THEME"])?$arParams["TEMPLATE_THEME"]:""),
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "N",
		"DISPLAY_PREVIEW_TEXT_MODE" => (isset($arParams["DETAIL_DISPLAY_PREVIEW_TEXT_MODE"])?$arParams["DETAIL_DISPLAY_PREVIEW_TEXT_MODE"]:""),
		"DETAIL_PICTURE_MODE" => (isset($arParams["DETAIL_DETAIL_PICTURE_MODE"])?$arParams["DETAIL_DETAIL_PICTURE_MODE"]:""),
		"ADD_TO_BASKET_ACTION" => $basketAction,
		"SHOW_CLOSE_POPUP" => isset($arParams["COMMON_SHOW_CLOSE_POPUP"])?$arParams["COMMON_SHOW_CLOSE_POPUP"]:"",
		"DISPLAY_COMPARE" => "Y",
		"COMPARE_PATH" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["compare"],
		"SHOW_BASIS_PRICE" => (isset($arParams["DETAIL_SHOW_BASIS_PRICE"])?$arParams["DETAIL_SHOW_BASIS_PRICE"]:"Y"),
		"COMPONENT_TEMPLATE" => "product_detail",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"OFFERS_LIMIT" => "0",
		"BACKGROUND_IMAGE" => "-",
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"STRICT_SECTION_CHECK" => "N",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"COMPATIBLE_MODE" => "Y",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"SET_VIEWED_IN_COMPONENT" => "N"
	),
	false
);

//Добавляем хлебные крошки товара
if (is_array($goods_chain_info) && isset($goods_chain_info['NAME']) && isset($goods_chain_info['DETAIL_PAGE_URL'])) {
    $APPLICATION->AddChainItem($goods_chain_info['NAME'], $goods_chain_info['DETAIL_PAGE_URL']);
} ?>