<?
$PERM["video"]["*"]="R";
$PERM["tg"]["2"]="D";
$PERM["tg"]["3"]="D";
$PERM["tg"]["4"]="D";
$PERM["tg"]["6"]="D";
$PERM["tg"]["5"]="D";
$PERM["tg"]["7"]="D";
$PERM["tg"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["7"]="T_8";
$PERM["/"]["*"]="R";
?>